#!/bin/sh

# immediately exit when error occurs
set -e

usage() {
	echo "usage: miner [-h] {factory_reset,run_recovery,fault_light} ..."
	echo
	echo "positional arguments:"
	echo "  {factory_reset,run_recovery,fault_light}"
	echo "    factory_reset       reboot and initiate factory reset"
	echo "    run_recovery        reboot to recovery mode"
	echo "    fault_light         turn on or off miner's fault LED"
	echo
	echo "optional arguments:"
	echo "  -h, --help            show this help message and exit"
}

factory_reset() {
	if [ $# -gt 0 ]; then
		echo "command 'factory_reset' does not take any argument"
		exit 1
	fi
	# erase U-Boot environment
	mtd erase uboot_env
	# U-Boot load default environment which initiate factory reset
	reboot
}

run_recovery() {
	set +e
	if [ $# -gt 0 ]; then
		echo "command 'run_recovery' does not take any argument"
		exit 1
	fi
	# check if uboot_env partition is not corrupted
	if [ -n "$(fw_printenv 2>&1 >/dev/null)" ]; then
		echo "U-Boot environment is corrupted and recovery mode cannot be run"
		echo "Factory reset can fix this issue"
		exit 1
	fi
	if [ $(uci get network.lan.proto) == 'static' ]; then
		net_ip=$(uci get network.lan.ipaddr 2>/dev/null)
		net_mask=$(uci get network.lan.netmask 2>/dev/null)
		net_gateway=$(uci get network.lan.gateway 2>/dev/null)
		net_dns_servers=$(uci get network.lan.dns 2>/dev/null | tr " " ,)
	fi
	net_hostname=$(uci get network.lan.hostname 2>/dev/null)
	# set 'recovery' variable in U-Boot environment
	fw_setenv --script - <<-EOF
		recovery=yes
		recovery_net_ip=$net_ip
		recovery_net_mask=$net_mask
		recovery_net_gateway=$net_gateway
		recovery_net_dns_servers=$net_dns_servers
		recovery_net_hostname=$net_hostname
	EOF
	# U-Boot boot from different partition whet variable 'recovery' is set
	reboot
}

fault_light() {
	if [ $# -ne 1 -o \( "$1" != 'on' -a "$1" != 'off' \) ]; then
		echo "command 'fault_light' takes only one argument [on|off]"
		exit 1
	fi
	# send 'on' or 'off' to cgminer_monitor
	echo $1 | nc localhost 4029 >/dev/null
}

# check number of arguments
if [ $# -lt 1 ]; then
	echo "missing command argument"
	exit 1
fi

# try to find command
command="$1"

case $command in
	factory_reset|run_recovery|fault_light)
		shift
		$command "$@"
	;;
	-h|--help)
		usage
	;;
	*)  # unknown command
		echo "unknown command '$command'"
		exit 1
	;;
esac
